# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8654b5707748926a279f4bc5aaa06281774c11e5317a1b4f33475d039ebcbc5c2ddfd7eaa84aed6d8b2793fc1ac7d5da66857cdafcd972b15d1e026893cf1b20

test:
  secret_key_base: 349f84f5b04562cb84bff647e8a9d033b869d822a24b028393aa4d10f62c8cd25398e6aed4436f0563c4c5a84096e2fdf766a45306cc1074ae2efeea8e8ac6ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
